name: Publish Ghost Docker Image

on:
    workflow_run:
        workflows: ['Node.js Package']
        types:
            - completed

jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkoutrepository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Set VERSION variable from package.json
              run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Wait for package availability
              id: wait-for-package
              run: |
                  PACKAGE_NAME="@667/ghost-storage-github"
                  TIMEOUT=300 # Timeout in seconds
                  INTERVAL=10 # Interval between checks in seconds
                  END=$((SECONDS+TIMEOUT))

                  while [ $SECONDS -lt $END ]; do
                      if npm info $PACKAGE_NAME@$VERSION > /dev/null 2>&1; then
                      echo "Package $PACKAGE_NAME@$VERSION is available!"
                      exit 0
                      fi
                      echo "Waiting for package $PACKAGE_NAME@$VERSION to be available..."
                      sleep $INTERVAL
                  done

                  echo "Package $PACKAGE_NAME@$VERSION did not become available in time."
                  exit 1

            - name: Build Docker image
              run: |
                docker build . \
                  -t june07/ghost-storage-github:latest \
                  -t june07/ghost-storage-github:$VERSION \
                  -t ghcr.io/june07/ghost-storage-github:latest \
                  -t ghcr.io/june07/ghost-storage-github:$VERSION
                docker save june07/ghost-storage-github:latest \
                    june07/ghost-storage-github:$VERSION \
                    ghcr.io/june07/ghost-storage-github:latest \
                    ghcr.io/june07/ghost-storage-github:$VERSION \
                    -o docker-image.tar
                
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Docker Image
                  path: docker-image.tar

    push-docker-hub:
        needs: build-docker
        runs-on: ubuntu-latest
        steps:
            - name: Set VERSION variable from package.json
              run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
              
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: june07
                password: ${{ secrets.DOCKER_PAT }}
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: Docker Image
                  path: .

            - name: Load image
              run: docker load -i docker-image.tar

            - name: Push Docker image (Docker Container Registry)
              run: |
                docker image ls
                docker push june07/ghost-storage-github:latest
                docker push june07/ghost-storage-github:${VERSION}
    push-ghcr:
        needs: build-docker
        runs-on: ubuntu-latest
        steps:
            - name: Set VERSION variable from package.json
              run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: Docker Image
                  path: .

            - name: Load image
              run: docker load -i docker-image.tar

            - name: Push Docker image (GitHub Container Registry)
              run: |
                docker image ls
                docker push ghcr.io/june07/ghost-storage-github:latest
                docker push ghcr.io/june07/ghost-storage-github:${VERSION}
